# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="bf697629-3f06-4c9c-b5c5-29047c203db1"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - job4jstudy@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always